### PR TITLE
Replace cas with cosign

### PR DESCRIPTION
**Pull request by pvizeli**

### CODE REVIEW

**Review by frenck — COMMENTED** [review]
Any reason we use this instead of a devcontainer feature?

<https://github.com/devcontainers-contrib/features/tree/main/src/cosign>

../Frenck

**Comment by pvizeli** [comment]
I guess we could refactor everything. But right now it works in that way. I'm fine to take it into icebox until someone have restructure it

**Comment by frenck** [comment]
Oh right, this repo only provides the base docker images, it is fine, though 👍 

../Frenck

**Comment by ludeeus** [comment]
On that note, everything in this repo could be converted into features instead of containers.

**Pull request merged**
